# Generated by Django 4.2.13 on 2024-07-13 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenso_app', '0002_remove_budget_end_date_remove_budget_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='period',
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
